cerbos:
  config:
    server:
      httpListenAddr: ":3592"
      grpcListenAddr: ":3593"
      adminAPI:
        enabled: true
        adminCredentials: # default credentials of cerbos:cerbosAdmin
          username: cerbos
          passwordHash: JDJ5JDEwJEdEOVFzZDE2VVhoVkR0N2VkUFBVM09nalc0QnNZaC9xc2E4bS9mcUJJcEZXenp5OUpjMi91Cgo=
    storage:
      driver: "git"
      git:
        protocol: https
        # Replace with the URL of your GitHub repo.
        url: https://github.com/cerbos/cerbos-argo-workflow.git
        branch: main
        subDir: cerbos
        checkoutDir: /work
        updatePollInterval: 0
    telemetry:
      disabled: true
